version: '3'

services:
  backend:
    build: 
      context: ./backend
    ports:
      - "8080:80"
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=sqlite:///./app.db
    networks:
      - app-network
    command:
      /start-reload.sh


networks:
  app-network:
    driver: bridge

